- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: yes

- name: Install Docker on Debian/Ubuntu
  apt:
    name: docker.io
    state: present
  when: docker_installed.rc != 0

- name: Install Docker on RHEL/CentOS
  yum:
    name: docker
    state: present
  when: docker_installed.rc != 0
