---
- name: Install Nginx and ensure Docker is functional
  hosts: all
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker on Debian/Ubuntu
      apt:
        name: docker.io
        state: present
      when: docker_installed.rc != 0

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Docker is running (directly on host)
      command: docker ps
      register: docker_running
      ignore_errors: yes

    - debug:
        var: docker_running.stdout
